-- MySQL Script generated by MySQL Workbench
-- Fri May 15 11:03:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ex1_BBDD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ex1_BBDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ex1_BBDD` DEFAULT CHARACTER SET utf8 ;
USE `ex1_BBDD` ;

-- -----------------------------------------------------
-- Table `ex1_BBDD`.`TAULAAVIONS_e1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`TAULAAVIONS_e1` (
  `id_avio_e1` INT NOT NULL AUTO_INCREMENT,
  `capacitat_e1` INT NOT NULL,
  `model_e1` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_avio_e1`),
  UNIQUE INDEX `id_avio_UNIQUE` (`id_avio_e1` ASC) VISIBLE,
  UNIQUE INDEX `capacitat_UNIQUE` (`capacitat_e1` ASC) VISIBLE,
  UNIQUE INDEX `model_UNIQUE` (`model_e1` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`TAULASEIENTS_e1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`TAULASEIENTS_e1` (
  `id_seients_e1` INT NOT NULL AUTO_INCREMENT,
  `TAULAAVIONS_id_avio_e1` INT NOT NULL,
  PRIMARY KEY (`id_seients_e1`, `TAULAAVIONS_id_avio_e1`),
  UNIQUE INDEX `id_seients_UNIQUE` (`id_seients_e1` ASC) VISIBLE,
  INDEX `fk_TAULASEIENTS_TAULAAVIONS1_idx` (`TAULAAVIONS_id_avio_e1` ASC) VISIBLE,
  CONSTRAINT `fk_TAULASEIENTS_TAULAAVIONS1`
    FOREIGN KEY (`TAULAAVIONS_id_avio_e1`)
    REFERENCES `ex1_BBDD`.`TAULAAVIONS_e1` (`id_avio_e1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`QUADRE_e2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`QUADRE_e2` (
  `id_quadre_e2` INT NOT NULL AUTO_INCREMENT,
  `preu_e2` DECIMAL(2) NOT NULL,
  `autor_e2` VARCHAR(70) NULL,
  PRIMARY KEY (`id_quadre_e2`),
  UNIQUE INDEX `autor_UNIQUE` (`autor_e2` ASC) VISIBLE,
  UNIQUE INDEX `preu_UNIQUE` (`preu_e2` ASC) VISIBLE,
  UNIQUE INDEX `id_quadre_UNIQUE` (`id_quadre_e2` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`COMPRADOR_e2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`COMPRADOR_e2` (
  `id_comprador_e2` INT NOT NULL AUTO_INCREMENT,
  `Nom_e2` VARCHAR(45) NULL,
  `Cognom_e2` VARCHAR(45) NULL,
  `DNI_e2` VARCHAR(9) NULL,
  `QUADRE_id_quadre_e2` INT NOT NULL,
  PRIMARY KEY (`id_comprador_e2`, `QUADRE_id_quadre_e2`),
  UNIQUE INDEX `id_comprador_UNIQUE` (`id_comprador_e2` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI_e2` ASC) VISIBLE,
  INDEX `fk_COMPRADOR_QUADRE1_idx` (`QUADRE_id_quadre_e2` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRADOR_QUADRE1`
    FOREIGN KEY (`QUADRE_id_quadre_e2`)
    REFERENCES `ex1_BBDD`.`QUADRE_e2` (`id_quadre_e2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`AUTOR_e4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`AUTOR_e4` (
  `idAUTOR_e4` INT NOT NULL AUTO_INCREMENT,
  `nomautor_e4` VARCHAR(45) NULL,
  `cognomautor_e4` VARCHAR(45) NULL,
  `direccio_e4` VARCHAR(150) NULL,
  `num_llibres_e4` INT NULL,
  PRIMARY KEY (`idAUTOR_e4`),
  UNIQUE INDEX `idAUTOR_UNIQUE` (`idAUTOR_e4` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`USUARI_e4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`USUARI_e4` (
  `idUsuari_e4` INT NOT NULL AUTO_INCREMENT,
  `nom_e4` VARCHAR(45) NOT NULL,
  `email_e4` VARCHAR(285) NOT NULL,
  `contrasenya_e4` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuari_e4`),
  UNIQUE INDEX `email_UNIQUE` (`email_e4` ASC) VISIBLE,
  UNIQUE INDEX `contrasenya_UNIQUE` (`contrasenya_e4` ASC) VISIBLE,
  UNIQUE INDEX `idUsuari_UNIQUE` (`idUsuari_e4` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`COMPRA_e4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`COMPRA_e4` (
  `id_compra_e4` INT NOT NULL AUTO_INCREMENT,
  `USUARI_e4_idUsuari_e4` INT NOT NULL,
  PRIMARY KEY (`id_compra_e4`),
  UNIQUE INDEX `id_compra_UNIQUE` (`id_compra_e4` ASC) VISIBLE,
  INDEX `fk_COMPRA_e4_USUARI_e41_idx` (`USUARI_e4_idUsuari_e4` ASC) VISIBLE,
  UNIQUE INDEX `USUARI_e4_idUsuari_e4_UNIQUE` (`USUARI_e4_idUsuari_e4` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA_e4_USUARI_e41`
    FOREIGN KEY (`USUARI_e4_idUsuari_e4`)
    REFERENCES `ex1_BBDD`.`USUARI_e4` (`idUsuari_e4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`LLIBRES_e4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`LLIBRES_e4` (
  `idLLIBRES_e4` INT NOT NULL AUTO_INCREMENT,
  `titol_e4` VARCHAR(70) NOT NULL,
  `unitats_e4` INT NOT NULL,
  `preu_e4` DECIMAL(2) NOT NULL,
  `AUTOR_e4_idAUTOR_e4` INT NOT NULL,
  `COMPRA_e4_id_compra_e4` INT NOT NULL,
  PRIMARY KEY (`idLLIBRES_e4`),
  UNIQUE INDEX `idLLIBRES_UNIQUE` (`idLLIBRES_e4` ASC) VISIBLE,
  INDEX `fk_LLIBRES_e4_AUTOR_e41_idx` (`AUTOR_e4_idAUTOR_e4` ASC) VISIBLE,
  INDEX `fk_LLIBRES_e4_COMPRA_e41_idx` (`COMPRA_e4_id_compra_e4` ASC) VISIBLE,
  CONSTRAINT `fk_LLIBRES_e4_AUTOR_e41`
    FOREIGN KEY (`AUTOR_e4_idAUTOR_e4`)
    REFERENCES `ex1_BBDD`.`AUTOR_e4` (`idAUTOR_e4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LLIBRES_e4_COMPRA_e41`
    FOREIGN KEY (`COMPRA_e4_id_compra_e4`)
    REFERENCES `ex1_BBDD`.`COMPRA_e4` (`id_compra_e4`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`Usuari_e5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`Usuari_e5` (
  `idUsuari_e5` INT NOT NULL AUTO_INCREMENT,
  `Nom_e5` VARCHAR(45) NOT NULL,
  `email_e5` VARCHAR(45) NOT NULL,
  `contrasenya_e5` VARCHAR(45) NOT NULL,
  `relacio_usuaris_e5` ENUM('familia', 'amics', 'altres') NOT NULL,
  PRIMARY KEY (`idUsuari_e5`),
  UNIQUE INDEX `idUsuari_UNIQUE` (`idUsuari_e5` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email_e5` ASC) VISIBLE,
  INDEX `fk_Usuari_e5_Usuari_e51_idx` (`relacio_usuaris_e5` ASC) VISIBLE,
  CONSTRAINT `fk_Usuari_e5_Usuari_e51`
    FOREIGN KEY (`relacio_usuaris_e5`)
    REFERENCES `ex1_BBDD`.`Usuari_e5` (`idUsuari_e5`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`PROVEÏDOR_e6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`PROVEÏDOR_e6` (
  `idPROVEÏDOR_e6` INT NOT NULL AUTO_INCREMENT,
  `nom_e6` VARCHAR(45) NOT NULL,
  `telèfon_e6` INT NULL,
  `fax_e6` INT NULL,
  `NIF_e6` VARCHAR(15) NULL,
  PRIMARY KEY (`idPROVEÏDOR_e6`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`ADREÇA_e6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`ADREÇA_e6` (
  `idADREÇA_e6` INT NOT NULL AUTO_INCREMENT,
  `carrer_e6` VARCHAR(45) NOT NULL,
  `número_e6` VARCHAR(45) NULL,
  `pis_e6` INT NULL,
  `porta_e6` VARCHAR(45) NULL,
  `ciutat_e6` VARCHAR(45) NOT NULL,
  `codi_postal_e6` INT NOT NULL,
  `pais_e6` VARCHAR(45) NOT NULL,
  `PROVEÏDOR_e6_idPROVEÏDOR_e6` INT NOT NULL,
  PRIMARY KEY (`idADREÇA_e6`, `PROVEÏDOR_e6_idPROVEÏDOR_e6`),
  INDEX `fk_ADREÇA_e6_PROVEÏDOR_e61_idx` (`PROVEÏDOR_e6_idPROVEÏDOR_e6` ASC) VISIBLE,
  CONSTRAINT `fk_ADREÇA_e6_PROVEÏDOR_e61`
    FOREIGN KEY (`PROVEÏDOR_e6_idPROVEÏDOR_e6`)
    REFERENCES `ex1_BBDD`.`PROVEÏDOR_e6` (`idPROVEÏDOR_e6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`Clients_e6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`Clients_e6` (
  `idClients_e6` INT NOT NULL AUTO_INCREMENT,
  `nom_client_e6` VARCHAR(45) NULL,
  `adreçaclient_e6` VARCHAR(200) NULL,
  `telèfonclient_e6` INT NULL,
  `emailclient_e6` VARCHAR(285) NULL,
  `data_registre_e6` DATE NULL,
  `recomanats_e6` INT NULL,
  PRIMARY KEY (`idClients_e6`),
  INDEX `fk_Clients_e6_Clients_e61_idx` (`recomanats_e6` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_e6_Clients_e61`
    FOREIGN KEY (`recomanats_e6`)
    REFERENCES `ex1_BBDD`.`Clients_e6` (`idClients_e6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`Venda_e6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`Venda_e6` (
  `idVenda_e6` INT NOT NULL AUTO_INCREMENT,
  `empleat_e6` VARCHAR(45) NOT NULL,
  `Clients_e6_idClients_e6` INT NOT NULL,
  PRIMARY KEY (`idVenda_e6`),
  INDEX `fk_Venda_e6_Clients_e61_idx` (`Clients_e6_idClients_e6` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_e6_Clients_e61`
    FOREIGN KEY (`Clients_e6_idClients_e6`)
    REFERENCES `ex1_BBDD`.`Clients_e6` (`idClients_e6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`Marca_e6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`Marca_e6` (
  `idMarca_e6` INT NOT NULL AUTO_INCREMENT,
  `nom_marca_e6` VARCHAR(45) NOT NULL,
  `PROVEÏDOR_e6_idPROVEÏDOR_e6` INT NOT NULL,
  UNIQUE INDEX `nom_marca_UNIQUE` (`nom_marca_e6` ASC) VISIBLE,
  UNIQUE INDEX `idMarca_UNIQUE` (`idMarca_e6` ASC) VISIBLE,
  PRIMARY KEY (`idMarca_e6`),
  INDEX `fk_Marca_e6_PROVEÏDOR_e61_idx` (`PROVEÏDOR_e6_idPROVEÏDOR_e6` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_e6_PROVEÏDOR_e61`
    FOREIGN KEY (`PROVEÏDOR_e6_idPROVEÏDOR_e6`)
    REFERENCES `ex1_BBDD`.`PROVEÏDOR_e6` (`idPROVEÏDOR_e6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`Ulleres_e6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`Ulleres_e6` (
  `idUlleres_e6` INT NOT NULL AUTO_INCREMENT,
  `graduacio_dreta_e6` FLOAT NOT NULL,
  `graduacio_esq_e6` FLOAT NOT NULL,
  `tipus_e6` ENUM('flotant', 'pasta', 'metalica') NOT NULL,
  `color montura_e6` VARCHAR(45) NULL,
  `color_esq_e6` VARCHAR(45) NULL,
  `color_dret_e6` VARCHAR(45) NULL,
  `preu_e6` DECIMAL(2) NOT NULL,
  `Venda_e6_idVenda_e6` INT NOT NULL,
  `Marca_e6_idMarca_e6` INT NOT NULL,
  PRIMARY KEY (`idUlleres_e6`, `Marca_e6_idMarca_e6`),
  UNIQUE INDEX `idUlleres_UNIQUE` (`idUlleres_e6` ASC) VISIBLE,
  INDEX `fk_Ulleres_e6_Venda_e61_idx` (`Venda_e6_idVenda_e6` ASC) VISIBLE,
  INDEX `fk_Ulleres_e6_Marca_e61_idx` (`Marca_e6_idMarca_e6` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_e6_Venda_e61`
    FOREIGN KEY (`Venda_e6_idVenda_e6`)
    REFERENCES `ex1_BBDD`.`Venda_e6` (`idVenda_e6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_e6_Marca_e61`
    FOREIGN KEY (`Marca_e6_idMarca_e6`)
    REFERENCES `ex1_BBDD`.`Marca_e6` (`idMarca_e6`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`USUARI_e3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`USUARI_e3` (
  `idUSUARI_e3` INT NOT NULL,
  `email_e3` VARCHAR(285) NULL,
  `contrasenya` VARCHAR(45) NULL,
  PRIMARY KEY (`idUSUARI_e3`),
  UNIQUE INDEX `idUSUARI_e3_UNIQUE` (`idUSUARI_e3` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`Videos_e3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`Videos_e3` (
  `idVideos_e3` INT NOT NULL,
  `descripcio_e3` VARCHAR(300) NULL,
  `titol_e3` VARCHAR(100) NULL,
  `USUARI_idUSUARI_e3` INT NOT NULL,
  PRIMARY KEY (`idVideos_e3`),
  INDEX `fk_Videos_USUARI1_idx` (`USUARI_idUSUARI_e3` ASC) VISIBLE,
  UNIQUE INDEX `USUARI_idUSUARI_e3_UNIQUE` (`USUARI_idUSUARI_e3` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_USUARI1`
    FOREIGN KEY (`USUARI_idUSUARI_e3`)
    REFERENCES `ex1_BBDD`.`USUARI_e3` (`idUSUARI_e3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex1_BBDD`.`FOTOGRAFIAS_e5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ex1_BBDD`.`FOTOGRAFIAS_e5` (
  `idFOTOGRAFIAS_e5` INT NOT NULL,
  `adreça_e5` VARCHAR(100) NULL,
  `url_e5` VARCHAR(45) NULL,
  `Usuari_e5_idUsuari_e5` INT NOT NULL,
  PRIMARY KEY (`idFOTOGRAFIAS_e5`, `Usuari_e5_idUsuari_e5`),
  INDEX `fk_FOTOGRAFIAS_e5_Usuari_e51_idx` (`Usuari_e5_idUsuari_e5` ASC) VISIBLE,
  CONSTRAINT `fk_FOTOGRAFIAS_e5_Usuari_e51`
    FOREIGN KEY (`Usuari_e5_idUsuari_e5`)
    REFERENCES `ex1_BBDD`.`Usuari_e5` (`idUsuari_e5`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
